### ISSUE TITLE
Add a list of ePartners to the About page

### ISSUE THREAD

**Issue by mattgd** [ACM-NCSU/ACM-NCSU.github.io#1]

**Comment by jkayani** [comment]
I didn't want to go through and list them all, esp. since the CSC dept. already has a list. I just linked to https://www.csc.ncsu.edu/corporate_relations/current-epartners.php instead - do you guys think that's enough?

**Comment by mattgd** [comment]
Yeah, I think that's sufficient. You can close it if you want, but maybe other want to weigh in.

**Comment by toombs-caeman** [comment]
Good enough for government work.

**Comment by jkayani** [comment]
The sponsors for our ACM/AITP chapter are distinct from the CSC e-Partners - something to fix on the About page.
