### ISSUE TITLE
Pre-event post for Docker workshop

### ISSUE THREAD

**Issue by jkayani** [ACM-NCSU/ACM-NCSU.github.io#9]
Exactly what the title says.

**Comment by toombs-caeman** [comment]
are you going to do the write-up or should I?

**Comment by jkayani** [comment]
It might be better if you do it since you have had more contact with the speaker than me. Go ahead and assign yourself. 

This brings up a good point though: Should the person who writes the pre-event post for a talk or workshop also write the post-event post?

**Comment by toombs-caeman** [comment]
I think the post-event post should be based more on who was at the event. It might be a good idea to decide who will do the post-event post at the event, before people start heading out.

I have created a page for the event. I would like to include the flyer, but I can't find it in the google docs. Not sure if Bryant added it or not.
